### ISSUE TITLE
missing icons

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/skeleton-navigation-kendo#3]
![image](https://cloud.githubusercontent.com/assets/2712405/12066607/9be33290-afb8-11e5-9ff2-61331142c898.png)

**Comment by JeroenVinke** [comment]
you need to append an exclamation mark: https://github.com/aurelia-ui-toolkits/skeleton-navigation-kendo/blob/master/src/app.html#L4-L5

https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues/88#issuecomment-161026605
